### ISSUE TITLE
How to install theme using key name?

### ISSUE THREAD

**Issue by jayabie** [fresns/themes#16]
I installed Fresns on a localhost, and i want to install moments through Key Name.
because the installation is not working through CL.

**Comment by jevantang** [comment]
The [Application Marketplace](https://marketplace.fresns.com/open-source) has been implemented and plugins and themes can be installed using the unikey, now you can install and use [Fresns v2.8](https://fresns.org/guide/install.html#download).

> PS: The official Community and Developer Centre are not yet live, so please wait until next week for them to go live.
